#pragma config(Sensor, dgtl1,  Speed,          sensorQuadEncoder)
#pragma config(Sensor, dgtl6,  button,         sensorTouch)
#pragma config(Motor,  port2,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          MotorA,        tmotorNone, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void displayEncoderValues ()
 {bLCDBacklight = true;

 displayLCDCenteredString(0,"RPM");
 	float ldec = SensorValue[Speed];
 	displayLCDNumber(1,1,ldec,2);

 	if (nLCDButtons == 2)
 	{
 		SensorValue[Speed] = 0;

 	}
 }

task main()
{

//	int prevTime, currTime;
//	currTime = nPgmTime;
//	while(true){
	displayEncoderValues ();

//		int prevValue, currValue;

//int RPM = (float)(currValue - prevValue)/360.0/((currTime - prevTime)/1000.0);
//displayLCDNumber(1,1,RPM,2);
//prevTime = nPgmTime;
//prevValue = SensorValue[Speed];



int prevValue, currValue;
int prevTime, currTime;
//int RPM = (float)(currValue - prevValue)/360.0/((currTime - prevTime)/1000.0);
prevTime = 2;
prevValue = sensorvalue[Speed];

wait1Msec(10);
while(true)
{
	if (SensorValue[button] == true)
	{
	motor[MotorA] = 127;
	}
	if (SensorValue[button] == false)
	{
		motor[MotorA] = 0;
	}
// 90 counts per revolution
    currValue = SensorValue[Speed];
   int RPM = (float)(currValue - prevValue)/360/((currTime - prevTime)/60000.0);

   // int RPM = (currValue - prevValue);

    displayLCDNumber(1,1,RPM, 5);

    prevTime = currTime;
    currTime = nPgmTime;
    prevValue = currValue;
    wait1Msec(10);
	}
}
