#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  LLiftEncode,    sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  RLiftEncode,    sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port2,           FR,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           BR,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           FL,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           BL,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           LLift,         tmotorVex393_MC29, PIDControl, encoderPort, I2C_1)
#pragma config(Motor,  port7,           RLift,         tmotorVex393_MC29, PIDControl, reversed, encoderPort, I2C_2)
#pragma config(Motor,  port8,           claw1,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           claw2,         tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int Level1 = 10;
int Level2 = 20;
int Level3 = 30;
int Level4 = 40;
int Level5 = 50;
int Level6 = 60;
int Level7 = 70;
int Level8 = 80;
int Level9 = 90;
int Level10 = 100;
int Level11 = 110;
int Level12 = 120;
int Level13 = 130;
int Level14 = 140;
int Level15 = 150;

void MoveToHeight(int Height)
{
			if(SensorValue[LLiftEncode] < Height)
			{
				motor[LLift] = 127;
				motor[RLift] = 127;
			}
			if(SensorValue[LLiftEncode] > Height)
			{
				motor[LLift] = -127;
				motor[RLift] = -127;
			}
			if(SensorValue[LLiftEncode] == Height)
			{
				motor[LLift] = 0;
				motor[RLift] = 0;
			}
}

task main()
{

	while (true)
	{
		//start tankdrive/Strafe
		motor[FR]=-vexRT[Ch2]+vexRT[Ch4];
		motor[BR]=-vexRT[Ch2]+-vexRT[Ch1];
		motor[FL]=vexRT[Ch3]+vexRT[Ch4];
		motor[BL]=-vexRT[Ch3]+vexRT[Ch1];
		//start tankdrive/Strafe

		if(vexRT[Btn5U])
			//start lift/claw
		{
			motor[LLift] = 127;
			motor[RLift] = 127;

		}
		else if(vexRT[Btn5D])
		{
			motor[LLift] = -127;
			motor[RLift] = -127;
		}
		else
		{
			motor[LLift] = 0;
			motor[RLift] = 0;
		}

		if(vexRT[Btn5UXmtr2])
		{
			motor[claw1] = 30;
			motor[claw2] = 30;
		}

		else if(vexRT[Btn5DXmtr2])
		{
			motor[claw1] = -30;
			motor[claw2] = -30;
		}
		else
		{
			motor[claw1] = 0;
			motor[claw2] = 0;
		}

		//end lift/claw

		//Encoders oh boy...

		if(vexRT[Btn6U])
		{
			//Clearing encoders attached to motors,
			nMotorEncoder[LLift] = 0;
			nMotorEncoder[RLift] = 0;
		}
		//lowest level
		if(vexRT[Btn7U])
		{
			while(SensorValue[LLiftEncode] > 0)
			{
				motor[LLift] = -127;
				motor[RLift] = -127;
			}
			while(SensorValue[LLiftEncode] < 0)
			{
				motor[LLift] = 0;
				motor[RLift] = 0;
			}

		}
		//next levels button
		if(vexRT[Btn7R])
		{
		MoveToHeight(Level1);
		}

		if(vexRT[Btn7D])
		{
		MoveToHeight(Level2);
		}

		if(vexRT[Btn7L])
		{
		MoveToHeight(Level3);
		}

		if(vexRT[Btn8U])
		{
		MoveToHeight(Level4);
		}

		if(vexRT[Btn8R])
		{
		MoveToHeight(Level5);
		}

		if(vexRT[Btn8D])
		{
		MoveToHeight(Level6);
		}

		if(vexRT[Btn8L])
		{
		MoveToHeight(Level7);
		}

		if(vexRT[Btn7UXmtr2])
		{
		MoveToHeight(Level8);
		}

		if(vexRT[Btn7RXmtr2])
		{
		MoveToHeight(Level9);
		}

		if(vexRT[Btn7DXmtr2])
		{
		MoveToHeight(Level10);
		}

		if(vexRT[Btn7LXmtr2])
		{
		MoveToHeight(Level11);
		}

		if(vexRT[Btn8UXmtr2])
		{
		MoveToHeight(Level12);
		}

		if(vexRT[Btn8RXmtr2])
		{
		MoveToHeight(Level13);
		}

		if(vexRT[Btn8DXmtr2])
		{
		MoveToHeight(Level14);
		}

		if(vexRT[Btn8LXmtr2])
		{
		MoveToHeight(Level15);
		}

}

}
