#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  LLiftEncode,    sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  RLiftEncode,    sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           claw1,         tmotorNone, openLoop)
#pragma config(Motor,  port2,           FR,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           BR,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           FL,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           BL,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           RTLift,        tmotorVex393_MC29, PIDControl, encoderPort, I2C_1)
#pragma config(Motor,  port7,           RBLift,        tmotorVex393_MC29, PIDControl, encoderPort, I2C_2)
#pragma config(Motor,  port8,           LTLift,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           LBLift,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          claw2,         tmotorNone, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int Level1 = 10;
int Level2 = 20;
int Level3 = 30;
int Level4 = 40;
int Level5 = 50;
int Level6 = 60;
int Level7 = 70;
int Level8 = 80;
int Level9 = 90;
int Level10 = 100;
int Level11 = 110;
int Level12 = 120;
int Level13 = 130;
int Level14 = 140;
int Level15 = 150;

void MoveToHeight(int Height)
{
			if(SensorValue[LLiftEncode] < Height)
			{
				motor[LTLift] = 127;
				motor[LBLift] = 127;

			}
			if(SensorValue[LLiftEncode] > Height)
			{
				motor[LTLift] = -127;
				motor[LBLift] = -127;
			}
			if(SensorValue[LLiftEncode] == Height)
			{
				motor[LTLift] = 0;
				motor[LBLift] = 0;
			}
}

task main()
{

	while (true)
	{
		//start tankdrive/Strafe
		motor[FR]=-vexRT[Ch2]+vexRT[Ch4];
		motor[BR]=-vexRT[Ch2]+-vexRT[Ch1];
		motor[FL]=vexRT[Ch3]+vexRT[Ch4];
		motor[BL]=-vexRT[Ch3]+vexRT[Ch1];
		//start tankdrive/Strafe

		if(vexRT[Btn5U])
			//start lift/claw
		{
			motor[LTLift] = 127;
			motor[LBLift] = 127;
			motor[RTLift] = 127;
			motor[RBLift] = 127;

		}
		else if(vexRT[Btn5D])
		{
			motor[LTLift] = -127;
			motor[LBLift] = -127;
			motor[RTLift] = -127;
			motor[RBLift] = -127;
		}
		else
		{
			motor[LTLift] = 0;
			motor[LBLift] = 0;
			motor[RTLift] = 0;
			motor[RBLift] = 0;
		}

		if(vexRT[Btn5U])
		{
			motor[claw1] = 127;
			motor[claw2] = 127;
		}

		else if(vexRT[Btn5D])
		{
			motor[claw1] = -127;
			motor[claw2] = -127;
	}
		else
		{
			motor[claw1] = 0;
			motor[claw2] = 0;
		}

		//end lift/claw

		//Encoders oh boy...

	}}
