#pragma config(Motor,  port1,           claw1,         tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           lift1,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           lift2,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           wheel1,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           wheel2,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           wheel3,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           wheel4,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           lift3,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           lift4,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          claw2,         tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while (true){
//comment tankdrive
motor[wheel1]=vexRT[Ch2];
motor[wheel2]=vexRT[Ch3];
motor[wheel3]=vexRT[Ch3];
motor[wheel4]=vexRT[Ch2];

if (vexRT[Btn5U])
//lift up
{
motor[lift1]= 127;
motor[lift2]= 127;
motor[lift3]= 127;
motor[lift4]= -127;
}
else if (vexRT[Btn5D])
//lift down
{
motor[lift1]= -127;
motor[lift2]= -127;
motor[lift3]= -127;
motor[lift4]= 127;
}
else
//stop from moving
{
motor[lift1]= 0;
motor[lift2]= 0;
motor[lift3]= 0;
motor[lift4]= 0;
}
if (vexRT[Btn6U])
{
motor [claw1] = 127;
motor [claw2] = 127;
}
else if (vexRT[Btn6D])
{
	motor[claw1] = -127;
	motor[claw2] = -127;
}
else
{
	motor[claw1] = 0;
	motor[claw1] = 0;
}
}}
