#pragma config(Sensor, dgtl1,  BL,             sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  BR,             sensorQuadEncoder)
#pragma config(Motor,  port1,           FL,            tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           BL,            tmotorVex393_MC29, openLoop, encoderPort, dgtl1)
#pragma config(Motor,  port3,           SL,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           SR,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           C,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           SL2,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           SR2,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           FR,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          BR,            tmotorVex393_HBridge, openLoop, encoderPort, dgtl3)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//FL = Front left wheel
//BL = Back left wheel
//SL = Scissor lift left
//SR = Scissor lift right
//C = Claw
//FR = Front right
//FL = Front left

task main()
{
	while (true){
		//Tank control
		//motor[FL] = vexRT[Ch3];
		//motor[BL] = vexRT[Ch3];
		//motor[FR] = vexRT[Ch2];
		//motor[BR] = vexRT[Ch2];

		//Strafing
		//The right joystick Y-axis controls the robot's forward and backward movement.
		//The right joystick X-axis controls the robot's left and right movement.
		//The left joystick X-axis controls the robot's rotation.
		motor[FL] = -vexRT[Ch1] - vexRT[Ch4] - vexRT[Ch2];
  	motor[BL] = -vexRT[Ch1] + vexRT[Ch4] + vexRT[Ch2];
		motor[FR] = -vexRT[Ch1] - vexRT[Ch4] + vexRT[Ch2];
    motor[BR] = -vexRT[Ch1] + vexRT[Ch4] - vexRT[Ch2];

    int sciSpeed = (vexRT[Btn8U] - vexRT[Btn8D])*(100*abs(vexRT[Btn8U]) + (27*abs(vexRT[Btn8D]))+20*(1-vexRT[Btn8D]);

    motor[SL] = sciSpeed;
    motor[SR] = sciSpeed;
    motor[SL2] = sciSpeed;
    motor[SR2] = sciSpeed;


    if(vexRT[Btn6U] == 1){
 			motor[C] = 50;
 		}

 		else if(vexRT[Btn6D] == 1){
 			motor[C] = -50;
 		}

 		else {
 		motor[C] = 0;
 		}
	}
}
