#pragma config(Motor,  port1,            ,             tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           FR,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           BR,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           FL,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           BL,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           wheel3,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           wheel4,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           lift3,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           lift4,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          claw2,         tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	bLCDBacklight = true;
	string mainBattery, backupBattery;

	while (true)
{
//comment tankdrive/Strafe
motor[FR]=vexRT[Ch2]+-vexRT[Ch4];
motor[BR]=vexRT[Ch2]+vexRT[Ch1];
motor[FL]=vexRT[Ch3]+vexRT[Ch4];
motor[BL]=vexRT[Ch3]+-vexRT[Ch1];

//LCD Module

		clearLCDLine(0);
		clearLCDLine(1);
		displayLCDString(0, 0, "Primary: ");
		sprintf(mainBattery, "%1.2f%c", nImmediateBatteryLevel/1000.0,'V');
		displayNextLCDString(mainBattery);

		displayLCDString(1, 0, "Backup: ");
		sprintf(backupBattery, "%1.2f%c", BackupBatteryLevel/1000.0, 'V');
		displayNextLCDString(backupBattery);

		wait1Msec(100);
	}
}
