#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    gyro,           sensorGyro)
#pragma config(Sensor, in2,    leftP,          sensorPotentiometer)
#pragma config(Sensor, in3,    rightP,         sensorPotentiometer)
#pragma config(Sensor, in4,    light,          sensorReflection)
#pragma config(Sensor, in5,    Battery,        sensorAnalog)
#pragma config(Sensor, dgtl1,  LED,            sensorDigitalOut)
#pragma config(Sensor, dgtl5,  LeftSonar,      sensorSONAR_cm)
#pragma config(Sensor, dgtl7,  rightSonar,     sensorSONAR_mm)
#pragma config(Sensor, dgtl9,  limitSwitch,    sensorTouch)
#pragma config(Sensor, dgtl10, Bumper,         sensorTouch)
#pragma config(Sensor, dgtl11, Red,            sensorLEDtoVCC)
#pragma config(Sensor, I2C_1,  leftBase,       sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  rightBase,      sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  LeftLift,       sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_4,  RightLift,      sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           CL,            tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           BR,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           RM,            tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port4,           FR,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           BL,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           LM,            tmotorVex393_MC29, openLoop, encoderPort, I2C_2)
#pragma config(Motor,  port7,           FL,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           LL,            tmotorVex393_MC29, openLoop, encoderPort, I2C_3)
#pragma config(Motor,  port9,           RL,            tmotorVex393_MC29, openLoop, encoderPort, I2C_4)
#pragma config(Motor,  port10,          CR,            tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

int autonomousMode = 1;
int driverControlModeCount = 1;
int degrees10 = 900;
int error = 5;



#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!
#pragma DebuggerWindows("VexLCD")

#pragma platform(VEX)

#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"

void clearLCD ()
{
	bLCDBacklight = true;
	clearLCDLine(0);
	clearLCDLine(1);
}
void ClearSensor ()
{
	SensorValue[leftBase] = 0;
	SensorValue[rightBase] = 0;
	sensorValue[LeftLift] =0;
}


//////////////////////////////////////////////DriverControl
void TankDrive()
{
SensorType[gyro] = sensorNone;
 SensorType[gyro] = sensorGyro;
	motor[FL]  = vexRT[Ch3];   // Left Joystick Y value
	motor[FR] = vexRT[Ch2];
	motor[BL]  = vexRT[Ch3];   // Left Joystick Y value
	motor[BR] = vexRT[Ch2];
	motor[LM]  = vexRT[Ch3];   // Left Joystick Y value
	motor[RM] = vexRT[Ch2];

	if ((vexRT[btn6U])&&(sensorvalue[LeftLift]>-1350))
	{
		motor[LL]= -127;
		motor[RL]= 127;
	}
	else if ((vexRT[btn6D])&&(sensorvalue[LeftLift]< 0))
	{

		motor[LL]= 127;
		motor[RL]= -127;

	}
	else
	{
		motor[LL]=0;
		motor[RL]=0;
	}


	if( vexRT[ Btn5D ])
	{
		motor[CR] = 80;
		motor[CL] = -80;
	}
	else if(vexRT[ Btn5U ])
	{
		motor[CL] = 80;
		motor[CR] = -80;
	}

	else
	{
		motor[CR] = 0;
		motor[CL] = 0;
	}

	if( vexRT[ Btn8R ])
	{
		ClearSensor();
}}








//////////////////////////////////////////////autonomous
void autonomous1 ()
{

	sensorvalue[leftBase]=0;
	sensorvalue[rightBase]=0;
	sensorvalue[LeftLift]=0;
		sensorvalue[RightLift]=0;


	while(sensorValue[RightLift] < 1350 && sensorValue[LeftLift]> -1350)
	{
		motor[Rl]=127;
		motor[LL]=-127:
	}
	{
			motor[Rl]=0;
		motor[LL]=0:

}}
void autonomous2 ()
{
}
void autonomous3 ()
{
}
void autonomous4 ()
{

}
void autonomous5 ()
{


}
void autonomous6 ()
{


}
void autonomous7 ()
{
}
void autonomous8 ()
{
}
void autonomous9 ()
{
}
void autonomous10 ()
{
}
void autonomous11 ()
{
}
void autonomous12 ()
{
}
void autonomousSelection ()
{
////////////////////////////////////////////////ClearLCD



clearLCD();

while (nLCDButtons != 2)
{
	displayLCDCenteredString(0,"Autonomous");
	displayLCDNumber(0,14,autonomousMode,2);
	displayLCDCenteredString(1,"<<  Selection >>");
	if (nLCDButtons == 1)
	{
		autonomousMode--;
		while(nLCDButtons == 1){wait1Msec(10);}
	}
	if (nLCDButtons == 4)
	{
		autonomousMode++;
		while(nLCDButtons == 4){wait1Msec(10);}
	}
	if (autonomousMode < 1)
	{
		autonomousMode = 12;
	}
	else if (autonomousMode > 12)
	{
		autonomousMode = 1;
	}
	wait1Msec(10);
}
clearLCD();
}

/////////////////////////////////////////////////////Nothing


void nothingOnScreen ()
{bLCDBacklight = true;
displayLCDCenteredString(0,"Currently");
displayLCDCenteredString(1,"Empty");
}
///////////////////////////////////////////////////////Batterydisplay
void displayBatteryValues ()

{bLCDBacklight = true;

string mainBatteryVoltage, backupBatteryVoltage;

displayLCDString(0,0,"Main:");

displayLCDString(1,0,"BackUp:");

sprintf(mainBatteryVoltage,"%1.2f%c",nImmediateBatteryLevel/1000.0,'V');

sprintf(backupBatteryVoltage,"%1.2f%c",BackupBatteryLevel/1000.0,'V');

displayLCDString(0,8,mainBatteryVoltage);

displayLCDString(1,8,backupBatteryVoltage);
}
//////////////////////////////////////////////////////SwapAuton

void swapAuton ()
{bLCDBacklight = true;
displayLCDCenteredString(0,"Autonomous");
displayLCDCenteredString(1,"Swap");
displayLCDNumber(0,14,autonomousMode,2);
if (nLCDButtons == 2)
{
	autonomousMode++;
	while(nLCDButtons == 2){wait1Msec(10);}
}
if (autonomousMode > 12)
{
	autonomousMode = 1;
}
}
/////////////////////////////////////////////////////Start Acton
void startAuton ()
{bLCDBacklight = true;
displayLCDCenteredString(0,"press to");
displayLCDCenteredString(1,"start autonomous");
}
//////////////////////////////////////////////////////GYRO
void gyroValue ()
{bLCDBacklight = true;
displayLCDCenteredString(0,"Gyro Value");
displayLCDNumber(1,5,SensorValue[gyro],5);
if (nLCDButtons == 2)
{bLCDBacklight = true;
	SensorType[gyro]=sensorNone;
	wait1Msec(1200);
	SensorType[gyro]=sensorGyro;
	wait1Msec(2000);
}
}
////////////////////////////////////////////////////Potentiometer
void displayPotentiometerValues ()
{bLCDBacklight = true;
displayLCDCenteredString(0,"Pot Values");
displayLCDNumber(1,2,SensorValue[leftP],4);
displayLCDNumber(1,10,SensorValue[rightP],4);
}
////////////////////////////////////////////////////Encoders
void displayEncoderValues ()
{
displayLCDCenteredString(0,"Left    Right");
displayLCDNumber(1,1,SensorValue[leftBase],5);
displayLCDNumber(1,9,SensorValue[rightBase],5);
if (nLCDButtons == 2)
{
	SensorValue[leftBase] = 0;
	SensorValue[rightBase] = 0;
}
}
void displayLiftEncoderValues ()
{
displayLCDCenteredString(0," lift Left Right");
displayLCDNumber(1,1,SensorValue[LeftLift],5);
displayLCDNumber(1,9,SensorValue[RightLift],5);
if (nLCDButtons == 2)
{
	SensorValue[LeftLift] = 0;
		SensorValue[RightLift] = 0;


}}
////////////////////////////////////////////////////[ColorSensorValue]

void displayColorSensorValue()
{bLCDBacklight = true;
displayLCDCenteredString(0,"Color Sensor");
displayLCDNumber(1,6,SensorValue[light],4);
}
////////////////////////////////////////////////////[UltrasonicValues]
void displayUltrasonicValues ()
{bLCDBacklight = true;
displayLCDCenteredString(0,"Ultrasonics");
displayLCDNumber(1,2,SensorValue[leftSonar],4);
displayLCDNumber(1,9,SensorValue[rightSonar],4);
}
////////////////////////////////////////////////////[DigitalInputs]
void displayDigitalInputs ()
{bLCDBacklight = true;
displayLCDCenteredString(0,"Digital Inputs");
displayLCDNumber(1,3,SensorValue[Bumper],1);
displayLCDNumber(1,9,SensorValue[limitSwitch],1);
}
////////////////////////////////////////////////////
task driverControlViewValues ()
{bLCDBacklight = true;
clearLCD ();
while (true)
{

	if (nLCDButtons == 1)
	{
		driverControlModeCount--;
		clearLCD ();
		while(nLCDButtons == 1){wait1Msec(10);}
	}
	if (nLCDButtons == 4)
	{
		driverControlModeCount++;
		clearLCD ();
		while(nLCDButtons == 4){wait1Msec(10);}
	}
	if (driverControlModeCount < 1)
	{
		driverControlModeCount = 12;
	}
	else if (driverControlModeCount > 12)
	{
		driverControlModeCount = 1;
	}

	switch (driverControlModeCount)
	{
	case 1:
		displayBatteryValues();
		break;
	case 2:
		swapAuton();
		break;
	case 3:
		startAuton();
		break;
	case 4:
		gyroValue();
		break;
	case 5:
		displayPotentiometerValues();
		break;
	case 6:
		displayEncoderValues();
		break;
	case 7:
		displayColorSensorValue();
		break;
	case 8:
		displayUltrasonicValues();
		break;
	case 9:
		displayDigitalInputs();
		break;
	case 10:
		displayLiftEncoderValues();
		break;
	case 11:
		nothingOnScreen();
		break;
	case 12:
		nothingOnScreen();
		break;
	}
	wait1Msec(10);
}

}
/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{bStopTasksBetweenModes = true;
autonomousSelection ();}
// Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
// Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.

// All activities that occur before the competition starts
// Example: clearing encoders, setting servo positions, ...


/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
if (autonomousMode == 1)
{
	autonomous1();
}
else if (autonomousMode == 2)
{
	autonomous2();
}
else if (autonomousMode == 3)
{
	autonomous3();
}
else if (autonomousMode == 4)
{
	autonomous4();
}
else if (autonomousMode == 5)
{
	autonomous5();
}
else if (autonomousMode == 6)
{
	autonomous6();
}
else if (autonomousMode == 7)
{
	autonomous7();
}
else if (autonomousMode == 8)
{
	autonomous8();
}
else if (autonomousMode == 9)
{
	autonomous9();
}
else if (autonomousMode == 10)
{
	autonomous10();
}
else if (autonomousMode == 11)
{
	autonomous11();
}
else if (autonomousMode == 12)
{
	autonomous12();
}
}
// .....................................................................................
// Insert user code here.
// .....................................................................................


/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
clearLCD();
startTask(driverControlViewValues);
while (true)
{

	TankDrive ();

	if ((driverControlModeCount==3&&nLCDButtons==2)||vexRT[Btn7R]==1)
	{
		startTask(autonomous);
		wait1Msec(15000);
		stopTask(autonomous);
	}
	wait1Msec(20);

}}
